/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AventuraRouteImport } from './routes/aventura'
import { Route as IndexRouteImport } from './routes/index'

const AventuraRoute = AventuraRouteImport.update({
  id: '/aventura',
  path: '/aventura',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aventura': typeof AventuraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aventura': typeof AventuraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aventura': typeof AventuraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aventura'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aventura'
  id: '__root__' | '/' | '/aventura'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AventuraRoute: typeof AventuraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/aventura': {
      id: '/aventura'
      path: '/aventura'
      fullPath: '/aventura'
      preLoaderRoute: typeof AventuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AventuraRoute: AventuraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
